spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pantrypal
    username: root
    password: alma
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update  # This is fine, tells Hibernate to update schema
    show-sql: true  # This enables SQL logging
    properties:
      hibernate:
        format_sql: true  # This formats the SQL queries for better readability
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
